In [1]:
import numpy as np

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

In [2]:
np.random.seed(43)
W1 = np.random.randn(2, 2)
b1 = np.zeros((1, 2))
W2 = np.random.randn(2, 1)
b2 = np.zeros((1, 1))

In [ ]:
learning_rate = 0.1
epochs = 10000

#treating it as a classification problem and using binary cross entropy loss instead of mean squared error
for epoch in range(epochs):
    Z1 = np.dot(X, W1) + b1
    A1 = 1 / (1 + np.exp(-Z1))

    Z2 = np.dot(A1, W2) + b2
    y_hat = 1 / (1 + np.exp(-Z2))

    loss = -np.mean(y * np.log(y_hat + 1e-8) + (1 - y) * np.log(1 - y_hat + 1e-8))

    dZ2 = y_hat - y
    dW2 = np.dot(A1.T, dZ2)
    db2 = np.sum(dZ2, axis=0, keepdims=True)

    dA1 = np.dot(dZ2, W2.T)
    dZ1 = dA1 * A1 * (1 - A1)
    dW1 = np.dot(X.T, dZ1)
    db1 = np.sum(dZ1, axis=0, keepdims=True)

    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1

    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")


Epoch 0, Loss: 0.7015
Epoch 1000, Loss: 0.1417
Epoch 2000, Loss: 0.0234
Epoch 3000, Loss: 0.0121
Epoch 4000, Loss: 0.0081
Epoch 5000, Loss: 0.0060
Epoch 6000, Loss: 0.0048
Epoch 7000, Loss: 0.0040
Epoch 8000, Loss: 0.0034
Epoch 9000, Loss: 0.0030


In [4]:
print("\nFinal Predictions:")
print(np.round(y_hat, 3))

print("\nPredicted Output:")
print((y_hat > 0.5).astype(int))

print("\nActual Output:")
print((y))


Final Predictions:
[[0.002]
 [0.998]
 [0.998]
 [0.004]]

Predicted Output:
[[0]
 [1]
 [1]
 [0]]

Actual Output:
[[0]
 [1]
 [1]
 [0]]
