In [1]:
import torch
print(torch.__version__)

2.9.0+cpu


## Creating a Tensor

In [3]:
# using empty
a = torch.empty(2,3)
a

tensor([[-2.6715e-30,  4.3352e-41, -2.6715e-30],
        [ 4.3352e-41, -1.2844e-30,  4.3352e-41]])

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
# Draws numbers from a Uniform distribution on the interval [0,1)
torch.rand(3,4)

tensor([[0.5827, 0.3887, 0.5936, 0.3994],
        [0.9466, 0.8651, 0.0398, 0.5807],
        [0.0302, 0.1952, 0.8764, 0.7897]])

In [13]:
torch.randn(3,4)
# Draws numbers from a Standard Normal distribution (Bell Curve) with mean 0 and variance 1.
# used for initialising weights while building Multi layer perceptron

tensor([[-0.3255, -0.1283, -1.0126,  0.9281],
        [-1.3380, -0.8782, -0.2379,  0.1637],
        [-0.7912,  1.9216, -0.1457, -1.1447]])

In [16]:
# using manual_seed
torch.manual_seed(100)
torch.randn(3,3)

tensor([[ 0.3607, -0.2859, -0.3938],
        [ 0.2429, -1.3833, -2.3134],
        [-0.3172, -0.8660,  1.7482]])

In [17]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
# identity matrix
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

## Tensor Shapes

In [20]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [29]:
torch.ones_like(x)
# same dimensions as x

tensor([[1, 1, 1],
        [1, 1, 1]])

In [22]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
torch.randn_like(x, dtype=torch.float32)

tensor([[ 0.4612, -0.9014, -0.2675],
        [ 0.0756,  1.2792, -1.5497]])

## Mathematical Operations

In [31]:
x = torch.rand(4,3)
x

tensor([[0.6896, 0.3687, 0.9053],
        [0.8356, 0.3039, 0.6726],
        [0.5740, 0.9233, 0.9178],
        [0.7590, 0.7775, 0.6179]])

In [32]:
# addition and subtraction
x + 2

tensor([[2.6896, 2.3687, 2.9053],
        [2.8356, 2.3039, 2.6726],
        [2.5740, 2.9233, 2.9178],
        [2.7590, 2.7775, 2.6179]])

In [33]:
# multiplication and division
x * 3

tensor([[2.0688, 1.1062, 2.7158],
        [2.5067, 0.9117, 2.0179],
        [1.7219, 2.7699, 2.7534],
        [2.2771, 2.3326, 1.8536]])

In [34]:
# int division
(x * 100)//3

tensor([[22., 12., 30.],
        [27., 10., 22.],
        [19., 30., 30.],
        [25., 25., 20.]])

In [35]:
# mod
((x * 100)//3)%2

tensor([[0., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 1., 0.]])

In [36]:
# power
x**2

tensor([[0.4756, 0.1360, 0.8195],
        [0.6982, 0.0924, 0.4524],
        [0.3294, 0.8525, 0.8424],
        [0.5761, 0.6045, 0.3818]])

## Element wise operations

In [40]:
torch.manual_seed(42) # again using the concept of seeding
a = torch.rand(2,3)
b = torch.rand(2,3)
a,b

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]),
 tensor([[0.2566, 0.7936, 0.9408],
         [0.1332, 0.9346, 0.5936]]))

In [41]:
a+b

tensor([[1.1388, 1.7086, 1.3236],
        [1.0925, 1.3250, 1.1945]])

In [42]:
a*b

tensor([[0.2264, 0.7262, 0.3602],
        [0.1278, 0.3649, 0.3567]])

In [44]:
a//b

tensor([[3., 1., 0.],
        [7., 0., 1.]])

In [45]:
a%b

tensor([[0.1126, 0.1214, 0.3829],
        [0.0270, 0.3904, 0.0073]])

In [46]:
a/b

tensor([[3.4387, 1.1529, 0.4070],
        [7.2028, 0.4178, 1.0123]])

In [53]:
c = torch.tensor([[1,-2.3],[-3,4.7]])
c

tensor([[ 1.0000, -2.3000],
        [-3.0000,  4.7000]])

In [54]:
torch.abs(c)

tensor([[1.0000, 2.3000],
        [3.0000, 4.7000]])

In [55]:
torch.neg(c)

tensor([[-1.0000,  2.3000],
        [ 3.0000, -4.7000]])

In [56]:
c

tensor([[ 1.0000, -2.3000],
        [-3.0000,  4.7000]])

In [60]:
torch.round(c)
# the nearest integer

tensor([[ 1., -2.],
        [-3.,  5.]])

In [57]:
torch.ceil(c)
# smallest integer just greater than or equal to the number

tensor([[ 1., -2.],
        [-3.,  5.]])

In [58]:
torch.floor(c)
# largest integer just less than or equal to the number

tensor([[ 1., -3.],
        [-3.,  4.]])

In [59]:
torch.clamp(c, min=-2.5, max=2.5)

tensor([[ 1.0000, -2.3000],
        [-2.5000,  2.5000]])

## Statistics

In [61]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[0., 4., 1.],
        [2., 5., 5.]])

In [62]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([ 5., 12.])

In [63]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([1.0000, 4.5000, 3.0000])

In [64]:
# median
torch.median(e)

tensor(2.)

In [65]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [66]:
# standard deviation
torch.std(e)

tensor(2.1370)

In [67]:
# variance
torch.var(e)

tensor(4.5667)

In [68]:
# argmax
torch.argmax(e)

tensor(4)

In [69]:
# argmin
torch.argmin(e)

tensor(0)

## Matrix Operations

In [78]:
m = torch.randint(size=(2,3), low=0, high=10)
n = torch.randint(size=(3,3), low=0, high=10)
print(m)
print(n)

tensor([[2, 0, 5],
        [9, 3, 4]])
tensor([[9, 6, 2],
        [0, 6, 2],
        [7, 9, 7]])


In [79]:
# matrix multiplcation
torch.matmul(m, n)

tensor([[ 53,  57,  39],
        [109, 108,  52]])

In [80]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product --> done between 1-D vectors
torch.dot(vector1, vector2)

tensor(11)

In [81]:
# transpose
torch.transpose(m, 0, 1)

tensor([[2, 9],
        [0, 3],
        [5, 4]])

In [86]:
# determinant (works for floating point tensor as an input)
n = n.to(torch.float32) # converting n to floating point from int.
torch.det(n)

tensor(216.0000)

In [88]:
# inverse
torch.inverse(n)

tensor([[ 1.1111e-01, -1.1111e-01,  5.3810e-09],
        [ 6.4815e-02,  2.2685e-01, -8.3333e-02],
        [-1.9444e-01, -1.8056e-01,  2.5000e-01]])

## Special Functions( Activation Functions also)

In [89]:
z = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
z

tensor([[3., 3., 4.],
        [3., 7., 0.]])

In [90]:
# log
torch.log(z)

tensor([[1.0986, 1.0986, 1.3863],
        [1.0986, 1.9459,   -inf]])

In [91]:
# exp
torch.exp(z)

tensor([[2.0086e+01, 2.0086e+01, 5.4598e+01],
        [2.0086e+01, 1.0966e+03, 1.0000e+00]])

In [92]:
# sqrt
torch.sqrt(z)

tensor([[1.7321, 1.7321, 2.0000],
        [1.7321, 2.6458, 0.0000]])

In [93]:
# sigmoid
torch.sigmoid(z)

tensor([[0.9526, 0.9526, 0.9820],
        [0.9526, 0.9991, 0.5000]])

In [94]:
# softmax
torch.softmax(z, dim=0)

tensor([[0.5000, 0.0180, 0.9820],
        [0.5000, 0.9820, 0.0180]])

In [95]:
# relu
torch.relu(z)

tensor([[3., 3., 4.],
        [3., 7., 0.]])

## Inplace Operations

In [99]:
m = torch.randn(2,3, dtype=torch.float32)
m

tensor([[-0.7813,  0.2293, -1.2754],
        [-1.9245,  0.4336,  0.6641]])

In [101]:
n = torch.randn(2,3, dtype=torch.float32)
n

tensor([[ 0.9560, -1.0110, -0.3568],
        [ 0.7147, -0.2398,  0.2163]])

In [102]:
m+n
# A completely new tensor is created occupying memory

tensor([[ 0.5223, -1.4311, -1.3068],
        [-0.2867, -1.0117,  1.5597]])

In [103]:
m.add_(n)
# Inplace operation

tensor([[ 0.5223, -1.4311, -1.3068],
        [-0.2867, -1.0117,  1.5597]])

In [104]:
m

tensor([[ 0.5223, -1.4311, -1.3068],
        [-0.2867, -1.0117,  1.5597]])

In [105]:
torch.relu_(m)

tensor([[0.5223, 0.0000, 0.0000],
        [0.0000, 0.0000, 1.5597]])

In [106]:
m

tensor([[0.5223, 0.0000, 0.0000],
        [0.0000, 0.0000, 1.5597]])

## Copying a Tensor

In [107]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [108]:
b = a

In [109]:
b

tensor([1, 2, 3])

In [111]:
b[1]=9
b

tensor([1, 9, 3])

In [112]:
a

tensor([1, 9, 3])

In [115]:
id(a)

132874401283952

In [116]:
id(b)
# addresses of a & b are the same

132874401283952

In [113]:
c = a.clone()
# creating a clone

In [114]:
id(c)

132874401861536